repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.260
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
