services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./small_shop/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: small_shop
      POSTGRES_USER: small_shop
      POSTGRES_PASSWORD: small_shop

volumes:
  postgres_data: